wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 3.2.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1642488929
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      3:
      - 13
      4: 3.7.0
      5: 0.12.9
      6: 3.2.0
      8:
      - 5
